### ISSUE TITLE
Feathers should accept other type of data beside only the object type.

### ISSUE THREAD

**Issue by parnurzeal** [feathersjs/feathers-commons#26]
I am creating rest service that receiving raw url string and it returns error.
```First parameter for 'create' must be an object```

So, I think Feathers should not prohibit from sending other types of data. 
Seeing from the code, it allows only object data type.
https://github.com/feathersjs/feathers-commons/blob/master/src/arguments.js#L66

This should be restricted manually by users or (normally) by body-parser, instead.

**Comment by daffl** [comment]
Since pretty much anything is an Object in JavaScript, the only thing you can't send are primitives (Number, String, Boolean) and functions (since those are considered callbacks). I'd probably just wrap a primitive into an object (like `{ value: <primitive value> }`) - this should still be possible in a `before` hook.

Since many parts of the code assume objects here this would be a pretty major change with many side effects so I'm pretty hesitant to make it especially since there is a workaround.

**Comment by ekryski** [comment]
I agree. Thanks for the suggestion @parnurzeal but this isn't something we are going to change. I'd follow @daffl's suggestion. Closing.

**Comment by parnurzeal** [comment]
Thank you for the answers. This is fine for me.
But I think it should be documented as for my self I was puzzled for awhile and thought I did sth. wrong on body-parser  but it actually is feathers that doesnt allow this. And I have to take time to dig into the code...
